from pathlib import Path
import re, sys
R=Path(__file__).resolve().parents[1]

def read(rel): return (R/rel).read_text(encoding='utf-8',errors='ignore')
checks=[]
def check(name, cond): checks.append((name,bool(cond)))

pub=read('pubspec.yaml'); repo=read('lib/core/subscription/subscription_repository.dart'); secure=read('lib/core/security/secure_kv_store.dart')
store=read('lib/data/app_data_store.dart'); supui=read('lib/features/management/sections/customers_suppliers_section.dart')
auth=read('lib/core/auth_service.dart'); hasher=read('lib/core/security/local_credential_hasher.dart'); merge=read('lib/data/cloud_state_merge.dart')
sql='\n'.join(read(f'supabase/migrations/{p.name}') for p in sorted((R/'supabase/migrations').glob('*.sql')))
sql9=read('supabase/migrations/009_final_device_proof_and_acl_hardening.sql')

check('version_0_32_1_40','version: 0.32.1+40' in pub)
check('app_version_0_32_1',"appVersion = '0.32.1'" in repo)
check('secure_storage_dependency','flutter_secure_storage:' in pub)
check('pbkdf2_dependency','crypto:' in pub)
check('hive_dependency','hive_ce:' in pub and 'hive_ce_flutter:' in pub)
check('legacy_bool_safe','prefs.get(key)' in secure and 'prefs.getString(key)' not in secure)
check('secure_bool_coercion',"value is bool" in secure and "value ? '1' : '0'" in secure)
check('credential_hashing','CredentialHash.encode' in store and 'CredentialHash.verify' in auth)
check('pbkdf2_strength','_iterations = 120000' in hasher)
check('no_debug_provision_log','PROVISION OWNER ERROR' not in repo)
check('device_uid_random','Random.secure()' in repo and "List<int>.generate(24" in repo)
check('device_proof_random','_deviceProofKey' in repo and 'List<int>.generate(32' in repo)
check('device_proof_rpc',repo.count("'p_device_proof': await deviceProof()") >= 10)
for rpc in ['pos_activate_device_v3','pos_device_heartbeat_v3','pos_subscription_status_v3','pos_owner_status_v2','pos_provision_owner_v2','pos_owner_login_v2','pos_change_owner_password_v2','pos_available_plans_v2','pos_create_subscription_request_v2','pos_pull_store_state_v2','pos_push_store_state_v3','pos_reserve_sequence_block_v2']:
    check('rpc_client_'+rpc, f"'{rpc}'" in repo)
check('clock_rollback_guard','clockRollbackTolerance' in repo and 'lastObservedAt' in repo and 'isBefore' in repo)
check('server_time_only_lease',"if (serverTime == null) return;" in repo)
check('offline_three_days','offlineAccessWindow = Duration(days: 3)' in repo)

startup=read('lib/features/auth/startup_gate.dart')
first_run=read('lib/features/auth/first_run_activation_screen.dart')
admin_login=read('lib/features/auth/admin_login_screen.dart')
staff_login=read('lib/features/auth/staff_login_screen.dart')
check('remote_license_check_5s','_remoteLicenseCheckInterval = Duration(seconds: 5)' in startup)
check('license_guard_survives_navigation','(route) => route.isFirst' in admin_login and '(route) => route.isFirst' in staff_login)
check('license_guard_forces_return','_returnToStartupGate' in startup and 'popUntil((route) => route.isFirst)' in startup)
check('license_rechecks_on_resume','WidgetsBindingObserver' in startup and 'AppLifecycleState.resumed' in startup)
check('second_device_skips_owner_setup','final cloudOwner = await _repository.ownerStatus();' in first_run and 'if (cloudOwner.exists)' in first_run and 'await _repository.markFirstRunComplete();' in first_run)
check('local_checksum_backup','primaryChecksum' in store and 'backupChecksum' in store)
check('corrupt_copy_preserved','preserveCorruptPrimary' in store and '_localCorruptionDetected' in store)
check('cloud_conflict_retry','for (var attempt = 0; attempt < 3; attempt++)' in store and 'expectedRevision' in store)
check('cloud_merge_stable_ids','CloudStateMerge.diff' in store and 'CloudStateMerge.apply' in store and '_byId' in merge)
check('supplier_add_method','SupplierRecord? addSupplier' in store)
check('supplier_role_guard',"actorRole != 'owner' && actorRole != 'manager'" in store)
check('supplier_duplicate_guard','suppliers.any' in store and 'cleanPhone' in store)
check('supplier_sequence',"_nextSequenceValue('supplier')" in store)
check('supplier_audit',"action: 'supplier_created'" in store)
check('supplier_button_ar',"'إضافة مورد'" in supui)
check('supplier_button_en',"'Add supplier'" in supui)
check('supplier_dialog','_supplierDialog' in supui and 'store.addSupplier' in supui)
check('supplier_button_role','if (canManage)' in supui)
check('pgcrypto_extensions','create extension if not exists pgcrypto with schema extensions' in sql.lower())
check('no_unqualified_gensalt',not re.search(r'(?<![.\w])gen_salt\s*\(',sql))
check('sql_device_proof_column','device_proof_hash text' in sql9)
check('sql_proof_digest',"extensions.digest(btrim(p_device_proof), 'sha256')" in sql9)
check('sql_strict_resolver','pos_resolve_active_device_v2' in sql9)
check('sql_old_activation_revoked','revoke all on function public.pos_activate_device(text,text,text,text,text) from public, anon, authenticated' in sql9)
check('sql_old_login_revoked','revoke all on function public.pos_owner_login(text,text,text,text) from public, anon, authenticated' in sql9)
check('sql_new_login_granted','grant execute on function public.pos_owner_login_v2' in sql9)
check('sql_owner_rate_limit',"interval '15 minutes'" in sql9 and '>= 8' in sql9)
check('sql_state_rls','alter table public.pos_store_state enable row level security' in sql.lower())
check('sql_state_direct_denied','revoke all on table public.pos_store_state from anon, authenticated' in sql.lower())
check('sql_admin_anon_revoked','revoke all on function public.admin_delete_business(uuid) from public, anon' in sql9)
check('sql_schema_create_revoked','revoke create on schema public from public, anon, authenticated' in sql9)
check('no_service_role','service_role' not in '\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in R.rglob('*') if p.is_file() and p.suffix in {'.dart','.sql','.bat','.sh','.yaml','.yml'}).lower())
check('android_release_not_debug','signingConfigs.getByName("debug")' not in read('android/app/build.gradle.kts'))
check('android_key_template',(R/'android/key.properties.example').exists())
check('windows_installer_all_files','recursesubdirs createallsubdirs' in read('installer/THAMAN_POS_FINAL.iss'))
check('windows_installer_release_glob','runner\\Release\\*' in read('installer/THAMAN_POS_FINAL.iss'))
for script in ['BUILD_WINDOWS_RELEASE.bat','BUILD_ANDROID_RELEASE.bat','BUILD_WEB_RELEASE.bat','RUN_WINDOWS.bat','RUN_WEB.bat']:
    t=read(script); check('supabase_'+script, 'THAMAN_SUPABASE_URL' in t and 'THAMAN_SUPABASE_PUBLISHABLE_KEY' in t)
for script in ['BUILD_IOS_RELEASE.sh','BUILD_MACOS_RELEASE.sh','RUN_IOS.sh','RUN_MACOS.sh']:
    t=read(script); check('supabase_'+script, 'THAMAN_SUPABASE_URL' in t and 'THAMAN_SUPABASE_PUBLISHABLE_KEY' in t)
check('unit_secure_migration',(R/'test/secure_kv_store_test.dart').exists())
check('unit_offline_lease',(R/'test/subscription_offline_lease_test.dart').exists())
check('unit_cloud_merge',(R/'test/cloud_state_merge_test.dart').exists())
check('unit_credentials',(R/'test/local_credential_hasher_test.dart').exists())
check('unit_supplier','owner and manager can add a supplier' in read('test/app_data_store_test.dart'))

for name, ok in checks: print(('PASS' if ok else 'FAIL')+' | '+name)
passed=sum(ok for _,ok in checks)
print(f'\nTHAMAN V9.5 FINAL QA: {passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
