from pathlib import Path
import sys
R=Path(__file__).resolve().parents[1]
def read(rel): return (R/rel).read_text(encoding='utf-8',errors='ignore')
checks=[]
def c(name,cond): checks.append((name,bool(cond)))
pub=read('pubspec.yaml')
repo=read('lib/core/subscription/subscription_repository.dart')
ui=read('lib/features/management/sections/subscription_section.dart')
startup=read('lib/features/auth/startup_gate.dart')
sql=read('supabase/migrations/010_custom_plans_device_subscription_and_email_requests.sql')
edge=read('supabase/functions/custom-plan-request-email/index.ts')

c('version_0_33_0_41','version: 0.33.0+41' in pub)
c('app_version_0_33_0',"appVersion = '0.33.0'" in repo)
c('catalog_model_custom_fields',all(x in repo for x in ['isCustom','customDurationDays']))
c('catalog_rpc',"'pos_available_plans_v2'" in repo and 'fetchAvailablePlans' in repo)
c('catalog_loaded_in_ui','_refreshCatalog' in ui and '_plansCatalogCard' in ui)
c('current_plan_badge','باقتك الحالية' in ui and 'Current' in ui)
c('published_plans_text','الباقات المتاحة' in ui and 'العروض المطروحة' in ui)
c('plan_request_action','createSubscriptionRequest' in repo and '_requestPlan' in ui)
c('custom_request_form','طلب باقة مخصصة' in ui and 'المدة بالأيام' in ui and 'عدد الأجهزة' in ui and 'الميزانية المتوقعة' in ui)
c('custom_request_contact','رقم التواصل' in ui and 'البريد الإلكتروني' in ui)
c('custom_request_rpc',"'pos_create_custom_plan_request_v2'" in repo and 'createCustomPlanRequest' in repo)
c('custom_request_proof',"'p_device_proof': proof" in repo)
c('request_persist_then_email',repo.find("'pos_create_custom_plan_request_v2'") < repo.find("'custom-plan-request-email'"))
c('edge_function_exists',(R/'supabase/functions/custom-plan-request-email/index.ts').exists())
c('edge_recipient','albhtytymr6@gmail.com' in edge)
c('edge_resend','RESEND_API_KEY' in edge and 'https://api.resend.com/emails' in edge)
c('edge_device_proof','device_proof_hash' in edge and 'sha256Hex' in edge)
c('edge_html_escape','escapeHtml' in edge)
c('service_role_not_in_flutter','service_role' not in '\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in (R/'lib').rglob('*.dart')).lower())
c('sql_custom_private_catalog','coalesce(p.is_custom,false)=false' in sql and 'p.custom_business_id=v_business_id' in sql)
c('sql_custom_request','create or replace function public.pos_create_custom_plan_request_v2' in sql)
c('sql_request_size_guard','request_too_large' in sql)
c('sql_device_subscription_binding','subscription_id = v_subscription_id' in sql and 'subscription_id = coalesce(v_subscription_id, subscription_id)' in sql)
c('sql_cross_tenant_guard','modified client somehow learns its UUID' in sql)
c('sql_legacy_plan_request_stays_private',"revoke all on function public.pos_create_subscription_request(text,text,text,uuid,text)" in sql and 'from public, anon, authenticated' in sql)
c('verify_after_010',(R/'supabase/VERIFY_AFTER_010.sql').exists())
c('remote_enforcement_preserved','_remoteLicenseCheckInterval = Duration(seconds: 5)' in startup)
c('supplier_add_preserved','إضافة مورد' in read('lib/features/management/sections/customers_suppliers_section.dart'))

for name,ok in checks: print(('PASS' if ok else 'FAIL')+' | '+name)
passed=sum(ok for _,ok in checks)
print(f'\nTHAMAN POS V9.6 CUSTOM PLANS QA: {passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
