from pathlib import Path
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
checks=[]
def ck(name,ok): checks.append((name,bool(ok))); print(('PASS' if ok else 'FAIL')+' | '+name)
pub=t('pubspec.yaml'); repo=t('lib/core/subscription/subscription_repository.dart'); sec=t('lib/core/security/secure_kv_store.dart'); db=t('lib/data/local_state_database.dart'); shell=t('lib/features/management/management_shell.dart'); sub=t('lib/features/management/sections/subscription_section.dart'); dev=t('lib/features/management/sections/developer_section.dart'); login=t('lib/features/auth/admin_login_screen.dart'); gate=t('lib/features/auth/startup_gate.dart')
ck('version_0_34_0_43','version: 0.34.0+43' in pub)
ck('app_version_match',"static const appVersion = '0.34.0';" in repo)
ck('activation_v4',"'pos_activate_device_v4'" in repo)
ck('device_proof_strict','readStrict(_deviceProofKey)' in repo and 'writeStrict(_deviceProofKey' in repo)
ck('strict_store_no_fallback','Future<String?> readStrict' in sec and 'SecureStorageUnavailableException' in sec)
ck('encrypted_hive','HiveAesCipher' in db and 'thaman_pos_operational_v9_7_enc' in db)
ck('legacy_plaintext_deleted','_deleteLegacyBoxesFromDisk' in db and 'Remove plaintext legacy boxes' in db)
ck('server_time_remaining','estimatedServerNow' in repo and "serverTime: _date(map['server_time'])" in repo)
ck('minute_refresh','Timer.periodic(const Duration(minutes: 1)' in sub)
ck('actual_remaining_ui','المدة الفعلية المتبقية' in sub and '_formatRemaining' in sub)
ck('expiry_notification','تنبيه الاشتراك: متبقي فعليًا' in shell and 'expiryWarningDays' in shell)
ck('custom_request_chat','_openCustomRequestChat' in sub and 'sendCustomPlanRequestMessage' in repo)
ck('custom_request_unread','unreadOwnerCount' in repo and 'رسالة' in sub)
ck('forgot_password_admin_reset','تعيين كلمة مرور مؤقتة' in login and 'albhtytymr6@gmail.com' in login)
ck('forced_temp_password_change','mustChangePassword' in login and 'changeOwnerPassword' in login)
ck('developer_section','ManagementSection.developer' in shell and 'Zentrix' in dev and 'عمر نضال البحطيطي' in dev)
ck('developer_logo_asset','assets/zentrix_logo.png' in pub and (root/'assets/zentrix_logo.png').exists())
ck('developer_portrait_asset','assets/omar_nidal_albahtiti.png' in pub and (root/'assets/omar_nidal_albahtiti.png').exists())
ck('secure_storage_block_ui','secure_storage_unavailable' in gate)
ck('activation_rate_limit_ui','activation_rate_limited' in sub)
failed=[n for n,o in checks if not o]
print(f'\nTHAMAN POS V9.7 FINAL STATIC QA: {len(checks)-len(failed)}/{len(checks)} PASS')
raise SystemExit(1 if failed else 0)
