from pathlib import Path
import sys, re
R=Path(__file__).resolve().parents[1]
checks=[]
def ck(name, ok): checks.append((name,bool(ok)))
def txt(p): return (R/p).read_text(encoding='utf-8',errors='ignore')

pub=txt('pubspec.yaml'); repo=txt('lib/core/subscription/subscription_repository.dart')
auth=txt('lib/features/auth/admin_login_screen.dart'); chat=txt('lib/features/management/sections/subscription_section.dart')
secure=txt('lib/core/security/secure_kv_store.dart'); db=txt('lib/data/local_state_database.dart')
notif=txt('lib/core/notifications/subscription_notifications_io.dart')
gradle=txt('android/app/build.gradle.kts'); manifest=txt('android/app/src/main/AndroidManifest.xml')
dev=txt('lib/features/management/sections/developer_section.dart')
main=txt('lib/main.dart')

ck('version_0_35_0_44','version: 0.35.0+44' in pub)
ck('app_version_match',"static const appVersion = '0.35.0';" in repo)
ck('offline_24_hours','offlineAccessWindow = Duration(hours: 24)' in repo)
ck('activation_v4',"pos_activate_device_v4" in repo)
ck('device_proof_strict','readStrict(_deviceProofKey)' in repo and 'writeStrict(_deviceProofKey' in repo)
ck('hive_key_strict','readStrict(_encryptionKeyStoreKey)' in db and 'writeStrict(' in db)
ck('encrypted_hive','HiveAesCipher' in db and 'encryptionCipher:' in db)
ck('legacy_plaintext_cleanup','deleteBoxFromDisk' in db and '_legacyPrimaryBoxName' in db)
ck('notification_dependency','flutter_local_notifications: 19.5.0' in pub and 'timezone:' in pub)
ck('notification_init','SubscriptionNotificationService.instance.initialize()' in main)
ck('notification_schedule','zonedSchedule(' in notif and 'inexactAllowWhileIdle' in notif)
ck('notification_android_permission','POST_NOTIFICATIONS' in manifest and 'RECEIVE_BOOT_COMPLETED' in manifest)
ck('notification_receivers','ScheduledNotificationReceiver' in manifest and 'ScheduledNotificationBootReceiver' in manifest)
ck('notification_desugaring','isCoreLibraryDesugaringEnabled = true' in gradle and 'desugar_jdk_libs:2.1.4' in gradle)
ck('notification_icon',(R/'android/app/src/main/res/drawable/thaman_notification.png').exists())
ck('notification_keep',(R/'android/app/src/main/res/raw/keep.xml').exists())
ck('actual_server_time_remaining',"serverNow" in repo and 'expiryWarningDays' in repo)
ck('temp_password_expiry_model','temporaryPasswordExpiresAt' in repo)
ck('temp_password_expiry_ui','temporary_password_expired' in auth and 'صلاحية الكلمة المؤقتة' in auth)
ck('strong_new_owner_password',"RegExp(r'[A-Z]')" in auth and "RegExp(r'[a-z]')" in auth and "RegExp(r'[0-9]')" in auth)
ck('custom_chat_near_realtime','Duration(seconds: 4)' in chat and 'المحادثة تتحدث تلقائيًا' in chat)
ck('custom_request_background_sync','Duration(seconds: 15)' in chat and '_requestSyncTimer' in chat)
ck('message_rate_limit_ui','message_rate_limited' in chat)
ck('developer_page_version','THAMAN POS 0.35.0' in dev)
ck('developer_brand','Zentrix' in dev and 'عمر نضال البحطيطي' in dev)
ck('developer_assets',(R/'assets/zentrix_logo.png').exists() and (R/'assets/omar_nidal_albahtiti.png').exists())
ck('strict_secrets_no_fallback_doc','High-value secrets' in secure and 'never persisted to SharedPreferences' in secure)

passed=sum(v for _,v in checks)
for n,v in checks: print(('PASS' if v else 'FAIL'), '|', n)
print(f'\nTHAMAN POS V9.8 HARDENED STATIC QA: {passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
