-- THAMAN POS V9.5 / Admin V1.8
-- Final device-proof binding, RPC ACL hardening, and pgcrypto compatibility.
-- Fresh database: run AFTER 001..008.
-- Existing V9.4 database: run this migration once after 008.

create extension if not exists pgcrypto with schema extensions;

-- Devices are bound to a second, random installation secret. The raw proof is
-- generated by the client and stored in OS secure storage; only its SHA-256
-- digest is persisted in Supabase.
alter table public.devices
  add column if not exists device_proof_hash text,
  add column if not exists proof_bound_at timestamptz;

comment on column public.devices.device_proof_hash is
  'SHA-256 digest of the per-installation POS device proof; raw proof never leaves client secure storage except during validated RPC calls.';

-- Existing 007 deployments may have been created while pgcrypto lived only in
-- the extensions schema. Make their search path explicit before removing any
-- temporary public wrappers that may have been used during testing.
alter function public.pos_provision_owner(text,text,text,text,text,text,text)
  set search_path = pg_catalog, public, extensions;
alter function public.pos_change_owner_password(text,text,text,text,text)
  set search_path = pg_catalog, public, extensions;
alter function public.admin_reset_pos_owner_password(uuid,text)
  set search_path = pg_catalog, public, extensions;
alter function public.admin_reset_pos_owner_pin(uuid,text)
  set search_path = pg_catalog, public, extensions;

-- Recreate owner login with the rate limit introduced in 008 and an explicit
-- extensions.crypt reference. This also repairs databases that temporarily
-- exposed public.crypt during setup.
create or replace function public.pos_owner_login(
  p_activation_code text,
  p_device_uid text,
  p_email text,
  p_password text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_business_id uuid;
  v_owner public.pos_owner_accounts%rowtype;
  v_failures integer;
begin
  begin
    v_business_id := public.pos_valid_business_for_device(p_activation_code, p_device_uid);
  exception when others then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end;

  select count(*)::integer into v_failures
  from public.pos_owner_login_attempts
  where business_id = v_business_id
    and device_uid = btrim(p_device_uid)
    and lower(email) = lower(btrim(p_email))
    and success = false
    and attempted_at > now() - interval '15 minutes';

  if coalesce(v_failures, 0) >= 8 then
    return jsonb_build_object('ok', false, 'error', 'too_many_attempts');
  end if;

  select * into v_owner
  from public.pos_owner_accounts
  where business_id = v_business_id
    and lower(email) = lower(btrim(p_email))
  limit 1;

  if v_owner.id is null or not v_owner.active or
     extensions.crypt(coalesce(p_password,''), v_owner.password_hash) <> v_owner.password_hash then
    insert into public.pos_owner_login_attempts(business_id, device_uid, email, success)
    values(v_business_id, btrim(p_device_uid), lower(btrim(p_email)), false);
    return jsonb_build_object('ok', false, 'error', 'invalid_credentials');
  end if;

  insert into public.pos_owner_login_attempts(business_id, device_uid, email, success)
  values(v_business_id, btrim(p_device_uid), lower(btrim(p_email)), true);

  delete from public.pos_owner_login_attempts
  where business_id = v_business_id
    and device_uid = btrim(p_device_uid)
    and lower(email) = lower(btrim(p_email))
    and success = false;

  update public.pos_owner_accounts
  set last_login_at = now(), updated_at = now()
  where id = v_owner.id;

  return jsonb_build_object(
    'ok', true,
    'owner_id', v_owner.id,
    'business_id', v_business_id,
    'role', 'owner',
    'display_name', v_owner.display_name,
    'phone', v_owner.phone,
    'email', v_owner.email,
    'must_change_password', v_owner.must_change_password
  );
end;
$$;

-- Do not leave compatibility crypto helpers callable in public. They are not
-- required by the final schema.
do $$
begin
  if to_regprocedure('public.crypt(text,text)') is not null then
    execute 'revoke all on function public.crypt(text,text) from public, anon, authenticated';
    begin
      execute 'drop function public.crypt(text,text)';
    exception when dependent_objects_still_exist then
      null;
    end;
  end if;
  if to_regprocedure('public.gen_salt(text,integer)') is not null then
    execute 'revoke all on function public.gen_salt(text,integer) from public, anon, authenticated';
    begin
      execute 'drop function public.gen_salt(text,integer)';
    exception when dependent_objects_still_exist then
      null;
    end;
  end if;
end;
$$;

-- Internal strict resolver. A licensed device must present BOTH the stable UID
-- and the per-installation proof. This makes copying only SharedPreferences or
-- guessing/reusing a UID insufficient to impersonate another installation.
create or replace function public.pos_resolve_active_device_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text
) returns table(business_id uuid, subscription_id uuid)
language sql
stable
security definer
set search_path = ''
as $$
  select r.business_id, r.subscription_id
  from public.pos_resolve_active_device(p_activation_code, p_device_uid) r
  join public.devices d
    on d.business_id = r.business_id
   and d.device_uid = btrim(p_device_uid)
  where p_device_proof ~ '^[A-Fa-f0-9]{64}$'
    and d.device_proof_hash = encode(extensions.digest(btrim(p_device_proof), 'sha256'), 'hex')
  limit 1;
$$;
revoke all on function public.pos_resolve_active_device_v2(text,text,text)
  from public, anon, authenticated;

-- Activation is the one endpoint allowed to establish the proof for a device.
-- If the same UID is already proof-bound, a different proof is rejected before
-- the legacy activation function can mutate the row.
create or replace function public.pos_activate_device_v3(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_device_name text,
  p_platform text,
  p_app_version text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hash text;
  v_existing_hash text;
  v_result jsonb;
  v_device_id uuid;
begin
  if coalesce(btrim(p_device_proof),'') !~ '^[A-Fa-f0-9]{64}$' then
    return jsonb_build_object('ok', false, 'error', 'device_proof_invalid', 'server_time', now());
  end if;
  v_hash := encode(extensions.digest(btrim(p_device_proof), 'sha256'), 'hex');

  select d.device_proof_hash into v_existing_hash
  from public.subscriptions s
  join public.devices d on d.business_id = s.business_id
  where upper(s.activation_code) = upper(btrim(p_activation_code))
    and d.device_uid = btrim(p_device_uid)
  order by s.created_at desc
  limit 1;

  if v_existing_hash is not null and v_existing_hash <> v_hash then
    return jsonb_build_object('ok', false, 'error', 'device_proof_mismatch', 'server_time', now());
  end if;

  v_result := public.pos_activate_device(
    p_activation_code, p_device_uid, p_device_name, p_platform, p_app_version
  );
  if coalesce((v_result->>'ok')::boolean, false) = false then
    return v_result || jsonb_build_object('server_time', now());
  end if;

  begin
    v_device_id := nullif(v_result->>'device_id','')::uuid;
  exception when others then
    v_device_id := null;
  end;

  if v_device_id is null then
    select d.id into v_device_id
    from public.subscriptions s
    join public.devices d on d.business_id = s.business_id
    where upper(s.activation_code) = upper(btrim(p_activation_code))
      and d.device_uid = btrim(p_device_uid)
    order by s.created_at desc
    limit 1;
  end if;

  if v_device_id is null then
    return jsonb_build_object('ok', false, 'error', 'device_not_found', 'server_time', now());
  end if;

  update public.devices
  set device_proof_hash = coalesce(device_proof_hash, v_hash),
      proof_bound_at = coalesce(proof_bound_at, now())
  where id = v_device_id
    and (device_proof_hash is null or device_proof_hash = v_hash);

  if not found then
    return jsonb_build_object('ok', false, 'error', 'device_proof_mismatch', 'server_time', now());
  end if;

  return v_result || jsonb_build_object('server_time', now());
end;
$$;

-- Heartbeat also performs a one-time proof bind for devices upgraded from V9.4.
create or replace function public.pos_device_heartbeat_v3(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_app_version text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hash text;
  v_business_id uuid;
  v_existing_hash text;
  v_result jsonb;
begin
  if coalesce(btrim(p_device_proof),'') !~ '^[A-Fa-f0-9]{64}$' then
    return jsonb_build_object('ok', false, 'error', 'device_proof_invalid', 'server_time', now());
  end if;
  v_hash := encode(extensions.digest(btrim(p_device_proof), 'sha256'), 'hex');

  select r.business_id into v_business_id
  from public.pos_resolve_active_device(p_activation_code, p_device_uid) r;
  if v_business_id is null then
    return jsonb_build_object('ok', false, 'error', 'license_denied', 'server_time', now());
  end if;

  select device_proof_hash into v_existing_hash
  from public.devices
  where business_id = v_business_id and device_uid = btrim(p_device_uid)
  limit 1;

  if v_existing_hash is not null and v_existing_hash <> v_hash then
    return jsonb_build_object('ok', false, 'error', 'device_proof_mismatch', 'server_time', now());
  end if;

  v_result := public.pos_device_heartbeat(p_activation_code, p_device_uid, p_app_version);
  if coalesce((v_result->>'ok')::boolean, false) = false then
    return v_result || jsonb_build_object('server_time', now());
  end if;

  update public.devices
  set device_proof_hash = coalesce(device_proof_hash, v_hash),
      proof_bound_at = coalesce(proof_bound_at, now())
  where business_id = v_business_id
    and device_uid = btrim(p_device_uid)
    and (device_proof_hash is null or device_proof_hash = v_hash);

  return v_result || jsonb_build_object('server_time', now());
end;
$$;

create or replace function public.pos_subscription_status_v3(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_business_id uuid;
begin
  select r.business_id into v_business_id
  from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof) r;
  if v_business_id is null then
    return jsonb_build_object('ok', false, 'error', 'license_denied', 'server_time', now());
  end if;
  return public.pos_subscription_status(p_activation_code) || jsonb_build_object('server_time', now());
end;
$$;

create or replace function public.pos_owner_status_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_owner_status(p_activation_code, p_device_uid);
end;
$$;

create or replace function public.pos_provision_owner_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_display_name text,
  p_phone text,
  p_email text,
  p_password text,
  p_pin text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_provision_owner(
    p_activation_code, p_device_uid, p_display_name, p_phone, p_email, p_password, p_pin
  );
end;
$$;

create or replace function public.pos_owner_login_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_email text,
  p_password text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_owner_login(p_activation_code, p_device_uid, p_email, p_password);
end;
$$;

create or replace function public.pos_change_owner_password_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_email text,
  p_current_password text,
  p_new_password text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_change_owner_password(
    p_activation_code, p_device_uid, p_email, p_current_password, p_new_password
  );
end;
$$;

create or replace function public.pos_available_plans_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_available_plans(p_activation_code, p_device_uid);
end;
$$;

create or replace function public.pos_create_subscription_request_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_request_type text,
  p_requested_plan_id uuid,
  p_customer_note text default ''
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_create_subscription_request(
    p_activation_code, p_device_uid, p_request_type, p_requested_plan_id, p_customer_note
  );
end;
$$;

create or replace function public.pos_pull_store_state_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_pull_store_state(p_activation_code, p_device_uid);
end;
$$;

create or replace function public.pos_push_store_state_v3(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_snapshot jsonb,
  p_expected_revision bigint default 0
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_push_store_state_v2(
    p_activation_code, p_device_uid, p_snapshot, p_expected_revision
  );
end;
$$;

create or replace function public.pos_reserve_sequence_block_v2(
  p_activation_code text,
  p_device_uid text,
  p_device_proof text,
  p_kind text,
  p_block_size integer default 100,
  p_observed_minimum bigint default 0
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists(
    select 1 from public.pos_resolve_active_device_v2(p_activation_code, p_device_uid, p_device_proof)
  ) then
    return jsonb_build_object('ok', false, 'error', 'license_denied');
  end if;
  return public.pos_reserve_sequence_block(
    p_activation_code, p_device_uid, p_kind, p_block_size, p_observed_minimum
  );
end;
$$;

-- Critical rule: only the proof-aware public POS wrappers remain executable by
-- app roles. Legacy endpoints are private to SECURITY DEFINER wrappers so a
-- modified client cannot bypass proof binding by calling an older RPC directly.
revoke all on function public.pos_activate_device(text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.pos_activate_device_v2(text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.pos_device_heartbeat(text,text,text) from public, anon, authenticated;
revoke all on function public.pos_device_heartbeat_v2(text,text,text) from public, anon, authenticated;
revoke all on function public.pos_subscription_status(text) from public, anon, authenticated;
revoke all on function public.pos_subscription_status_v2(text,text) from public, anon, authenticated;
revoke all on function public.pos_owner_status(text,text) from public, anon, authenticated;
revoke all on function public.pos_provision_owner(text,text,text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.pos_owner_login(text,text,text,text) from public, anon, authenticated;
revoke all on function public.pos_change_owner_password(text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.pos_available_plans(text,text) from public, anon, authenticated;
revoke all on function public.pos_create_subscription_request(text,text,text,uuid,text) from public, anon, authenticated;
revoke all on function public.pos_pull_store_state(text,text) from public, anon, authenticated;
revoke all on function public.pos_push_store_state(text,text,jsonb) from public, anon, authenticated;
revoke all on function public.pos_push_store_state_v2(text,text,jsonb,bigint) from public, anon, authenticated;
revoke all on function public.pos_reserve_sequence_block(text,text,text,integer,bigint) from public, anon, authenticated;
revoke all on function public.pos_valid_business_for_device(text,text) from public, anon, authenticated;
revoke all on function public.pos_resolve_active_device(text,text) from public, anon, authenticated;

revoke all on function public.pos_activate_device_v3(text,text,text,text,text,text) from public;
revoke all on function public.pos_device_heartbeat_v3(text,text,text,text) from public;
revoke all on function public.pos_subscription_status_v3(text,text,text) from public;
revoke all on function public.pos_owner_status_v2(text,text,text) from public;
revoke all on function public.pos_provision_owner_v2(text,text,text,text,text,text,text,text) from public;
revoke all on function public.pos_owner_login_v2(text,text,text,text,text) from public;
revoke all on function public.pos_change_owner_password_v2(text,text,text,text,text,text) from public;
revoke all on function public.pos_available_plans_v2(text,text,text) from public;
revoke all on function public.pos_create_subscription_request_v2(text,text,text,text,uuid,text) from public;
revoke all on function public.pos_pull_store_state_v2(text,text,text) from public;
revoke all on function public.pos_push_store_state_v3(text,text,text,jsonb,bigint) from public;
revoke all on function public.pos_reserve_sequence_block_v2(text,text,text,text,integer,bigint) from public;

grant execute on function public.pos_activate_device_v3(text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.pos_device_heartbeat_v3(text,text,text,text) to anon, authenticated;
grant execute on function public.pos_subscription_status_v3(text,text,text) to anon, authenticated;
grant execute on function public.pos_owner_status_v2(text,text,text) to anon, authenticated;
grant execute on function public.pos_provision_owner_v2(text,text,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.pos_owner_login_v2(text,text,text,text,text) to anon, authenticated;
grant execute on function public.pos_change_owner_password_v2(text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.pos_available_plans_v2(text,text,text) to anon, authenticated;
grant execute on function public.pos_create_subscription_request_v2(text,text,text,text,uuid,text) to anon, authenticated;
grant execute on function public.pos_pull_store_state_v2(text,text,text) to anon, authenticated;
grant execute on function public.pos_push_store_state_v3(text,text,text,jsonb,bigint) to anon, authenticated;
grant execute on function public.pos_reserve_sequence_block_v2(text,text,text,text,integer,bigint) to anon, authenticated;

-- Tighten schema/function exposure. Admin RPCs remain callable only by an
-- authenticated session and each one still performs its own owner check.
revoke create on schema public from public, anon, authenticated;

revoke all on function public.is_thaman_owner() from public, anon;
revoke all on function public.create_subscriber_subscription(text,text,text,text,text,text,text,uuid,timestamptz,timestamptz,boolean,integer,text) from public, anon;
revoke all on function public.set_business_access_status(uuid,text) from public, anon;
revoke all on function public.set_subscription_access_status(uuid,text) from public, anon;
revoke all on function public.expire_due_subscriptions() from public, anon;
revoke all on function public.create_subscription_for_existing(uuid,uuid,timestamptz,timestamptz,boolean,integer,text) from public, anon;
revoke all on function public.renew_subscription(uuid,timestamptz) from public, anon;
revoke all on function public.admin_set_device_blocked(uuid,boolean,text) from public, anon;
revoke all on function public.admin_delete_device(uuid) from public, anon;
revoke all on function public.admin_delete_subscription(uuid) from public, anon;
revoke all on function public.admin_delete_payment(uuid) from public, anon;
revoke all on function public.admin_delete_plan(uuid) from public, anon;
revoke all on function public.admin_delete_business(uuid) from public, anon;
revoke all on function public.admin_set_subscription_request_status(uuid,text,text) from public, anon;
revoke all on function public.admin_reset_pos_owner_password(uuid,text) from public, anon;
revoke all on function public.admin_reset_pos_owner_pin(uuid,text) from public, anon;

grant execute on function public.is_thaman_owner() to authenticated;
grant execute on function public.create_subscriber_subscription(text,text,text,text,text,text,text,uuid,timestamptz,timestamptz,boolean,integer,text) to authenticated;
grant execute on function public.set_business_access_status(uuid,text) to authenticated;
grant execute on function public.set_subscription_access_status(uuid,text) to authenticated;
grant execute on function public.expire_due_subscriptions() to authenticated;
grant execute on function public.create_subscription_for_existing(uuid,uuid,timestamptz,timestamptz,boolean,integer,text) to authenticated;
grant execute on function public.renew_subscription(uuid,timestamptz) to authenticated;
grant execute on function public.admin_set_device_blocked(uuid,boolean,text) to authenticated;
grant execute on function public.admin_delete_device(uuid) to authenticated;
grant execute on function public.admin_delete_subscription(uuid) to authenticated;
grant execute on function public.admin_delete_payment(uuid) to authenticated;
grant execute on function public.admin_delete_plan(uuid) to authenticated;
grant execute on function public.admin_delete_business(uuid) to authenticated;
grant execute on function public.admin_set_subscription_request_status(uuid,text,text) to authenticated;
grant execute on function public.admin_reset_pos_owner_password(uuid,text) to authenticated;
grant execute on function public.admin_reset_pos_owner_pin(uuid,text) to authenticated;

-- A compact server-side self-check. Run manually if desired; it returns no
-- sensitive data and confirms the migration objects exist.
comment on function public.pos_resolve_active_device_v2(text,text,text) is
  'Internal THAMAN V9.5 proof-aware device resolver. Not executable by anon/authenticated.';
